stages:
  - build
  - test
  - push_to_dockerhub
  - deploy

build_job:
  stage: build
  script:
    - docker build -t notes-app:latest .
  tags:
    - dev

test_job:
  stage: test
  script:
    - echo "This is testing phase"
  tags:
    - dev

push_job:
  stage: push_to_dockerhub
  script:
    - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASS
    - docker image tag notes-app:latest $DOCKERHUB_USER/notes-app:latest
    - docker push $DOCKERHUB_USER/notes-app:latest
  tags:
    - dev

deploy_job:
  stage: deploy
  script:
    - docker compose up -d
  tags:
    - dev
